version: 0.2

phases:
  install:
    commands:
      - echo Installing kubectl...
      - curl -LO https://dl.k8s.io/release/v1.30.0/bin/linux/amd64/kubectl
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/
      - echo Installing AWS CLI v2...
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - sudo ./aws/install
      - echo Setup complete.
  
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 470397863283.dkr.ecr.us-east-1.amazonaws.com
      - echo Verifying AWS credentials...
      - aws sts get-caller-identity
      - echo Updating kubeconfig for EKS cluster...
      - aws eks update-kubeconfig --region us-east-1 --name trend-apps-cluster
      - echo Checking kubectl context and cluster nodes...
      - kubectl config current-context
      - kubectl get nodes

  build:
    commands:
      - echo Building Docker image...
      - docker build -t brain-tasks-app .
      - docker tag brain-tasks-app 470397863283.dkr.ecr.us-east-1.amazonaws.com/brain-tasks-app:latest

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push 470397863283.dkr.ecr.us-east-1.amazonaws.com/brain-tasks-app:latest
      - echo Deploying updated image to EKS...
      - kubectl set image deployment/brain-tasks-deployment brain-tasks-container=470397863283.dkr.ecr.us-east-1.amazonaws.com/brain-tasks-app:latest
      - echo Deployment complete.

artifacts:
  files:
    - '**/*'
