version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password | docker login --username AWS --password-stdin 470397863283.dkr.ecr.us-east-1.amazonaws.com/brain-tasks-app
  build:
    commands:
      - echo Build started on `date`
      - docker build -t brain-tasks-app .
      - docker tag brain-tasks-app 470397863283.dkr.ecr.us-east-1.amazonaws.com/brain-tasks-app:latest
  post_build:
    commands:
      - docker push <ecr_repo_uri>:latest
      - printf '[{"name":"brain-tasks","imageUri":"%s"}]' 470397863283.dkr.ecr.us-east-1.amazonaws.com/brain-tasks-app:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
