version: 0.2

phases:
  install:
    commands:
      - curl -LO https://dl.k8s.io/release/v1.30.0/bin/linux/amd64/kubectl
      - chmod +x kubectl && mv kubectl /usr/local/bin/
      - aws eks update-kubeconfig --name Brain-task-cluster --region us-east-1

  pre_build:
    commands:
      - aws ecr get-login-password | docker login --username AWS --password-stdin 470397863283.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - docker build -t brain-tasks-app .
      - docker tag brain-tasks-app 470397863283.dkr.ecr.us-east-1.amazonaws.com/brain-tasks-app:latest

  post_build:
    commands:
      - docker push 470397863283.dkr.ecr.us-east-1.amazonaws.com/brain-tasks-app:latest

artifacts:
  files:
    - deployment.yaml
    - service.yaml
